name: Goragitize
on:
  push:
    branches: [main]
jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: narze/goragit@main
        with:
          author_name: santhitak
          author_email: santhita.sk@gmail.com
          github_token_with_repo_scope: ${{ secrets.STUPID_HACKATHON }}
          i_understand_that_this_workflow_will_goragodize_my_repo: true
          keep_git_history_in_message: false
